name: nepvent_reward
description: "This Project is called Nepvent Reward."

# Prevents accidental publishing to pub.dev; remove if you wish to publish
publish_to: 'none'

# Versioning details for the application
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add asset images
  assets:
    - assets/images/
    - .env


  # Uncomment and configure the following section if you want to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

# For more details on this file, visit:
# https://dart.dev/tools/pub/pubspec
